@host = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{host}}/accounts
Content-Type: application/json

{
  "name": "Carlos Faustino",
  "email": "carlosfaustino@email.com",
  "password": "123456"
}

###

# @name authenticate
POST {{host}}/sessions
Content-Type: application/json

{
  "email": "carlosfaustino@email.com",
  "password": "123456"
}

###

# @name create_question
POST {{host}}/questions
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "Nova pergunta",
  "content": "Conteúdo da pergunta"
}

###

# @name fetch_recent_questions
GET {{host}}/questions?page=1
Authorization: Bearer {{authToken}}